# Generated by Django 4.1 on 2022-08-19 04:00

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_firstname', models.CharField(max_length=20)),
                ('student_lastname', models.CharField(max_length=20)),
                ('student_email', models.CharField(max_length=50, unique=True)),
                ('student_regnumber', models.CharField(default=main.models.random_reg_number, max_length=20)),
                ('student_sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
            ],
        ),
    ]
