# Generated by Django 4.1 on 2022-08-19 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
