# Generated by Django 4.1 on 2022-09-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_votes_alter_students_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='upvoted',
            field=models.CharField(default=1, max_length=3),
        ),
    ]
