# Generated by Django 4.1 on 2022-09-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_votes_upvoted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='upvoted',
            field=models.CharField(max_length=3),
        ),
    ]
