# Generated by Django 4.1 on 2022-09-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_votes_upvoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='uid',
            field=models.UUIDField(default=10),
        ),
    ]
